In [2]:
from sklearn import svm, datasets
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
df=pd.read_csv("Iris.csv")

In [14]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import average_precision_score
from sklearn.metrics import classification_report 
df = pd.read_csv("Iris.csv")
ds=np.array(df)
features=ds[:,:-1]
labels=ds[:,-1:]
X_Train,X_Test,y_Train,y_Test=train_test_split(features,labels,random_state=0)
clfr=DecisionTreeClassifier()
clfr.fit(X_Train,y_Train)
result=clfr.predict(X_Test)
#print(clfr.score(X_Test,y_Test))
setosa=df[df['Species']=='Iris-setosa']
versicolor=df[df['Species']=='Iris-versicolor']
virginica=df[df['Species']=='Iris-virginica']
#fig,ax=plt.subplots(nrows=1,ncols=2,figsize=(13,10))
results = confusion_matrix(y_Test, result) 
#Confusion Matrix 
print(results) 
#Accuracy Score 
print(accuracy_score(y_Test, result))
print(classification_report(y_Test, result))

[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]
0.9736842105263158
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.94      1.00      0.97        16
 Iris-virginica       1.00      0.89      0.94         9

       accuracy                           0.97        38
      macro avg       0.98      0.96      0.97        38
   weighted avg       0.98      0.97      0.97        38

